# Store Revenue Analysis Report

## Objective

Calculate the total revenue generated by each store.

## Query

```sql
-- Write your solution here
```

## Concepts

* Multiple INNER JOINs
* GROUP BY
* SUM()
* ORDER BY

## Business Insight

This report helps management compare the financial performance of each store by analyzing the revenue generated through customer payments.

## Skills Demonstrated

* Aggregating revenue data
* Working with multiple table relationships
* Applying GROUP BY in business scenarios
* Comparing store performance
